name: security-sast-semgrep

description: 'Run semgrep'

runs-on: ubuntu-latest

inputs:
  token:
    description: 'semgrep publish token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Semgrep
      id: semgrep
      uses: semgrep/semgrep-action@v1
      with:
        publishToken: ${{ inputs.token }}
